name: ResticMac
options:
  bundleIdPrefix: com.resticmac
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  developmentLanguage: en_GB

settings:
  base:
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_TESTABILITY: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY: YES
    CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER: YES
    CLANG_ANALYZER_NONNULL: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    RUN_CLANG_STATIC_ANALYZER: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE

packages:
  SwiftShell:
    url: https://github.com/kareman/SwiftShell.git
    from: 5.1.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    from: 1.5.3
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.2

targets:
  ResticMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: 
      - path: Sources/ResticMac
    dependencies:
      - package: SwiftShell
      - package: swift-log
        product: Logging
      - package: KeychainAccess
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.resticmac.app
        PRODUCT_NAME: ResticMac
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_ENTITLEMENTS: Sources/ResticMac/ResticMac.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_VERSION: 5.9

  ResticMacTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources: 
      - path: Tests/ResticMacTests
    dependencies:
      - target: ResticMac
      - package: SwiftShell
      - package: swift-log
        product: Logging
      - package: KeychainAccess
